server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    testWhileIdle: true
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  h2:
    console:
      enabled: true



