server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always

#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=123456
#spring.jpa.hibernate.ddl-auto=update
#spring.h2.console.enabled=true
